{
 "title": "prometheus",
 "description": "监控文章服务",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service_group", "label": "服务分组", "query": { "query": "label_values(service_group)" } },
   { "name": "env", "label": "环境", "query": { "query": "label_values(env)" } },
   { "name": "service_name", "label": "服务名", "query": { "query": "label_values(service_name)" } }
  ]
 },
 "panels": [
  {
   "title": "API-QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_duration_ms_count{env=\"$env\", service_group=\"$service_group\", service_name=\"$service_name\"}[2m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API-AVG-Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(increase(http_server_requests_duration_ms_sum{env=\"$env\", service_group=\"$service_group\", service_name=\"$service_name\"}[2m]) / increase(http_server_requests_duration_ms_count{env=\"$env\", service_group=\"$service_group\", service_name=\"$service_name\"}[2m]) > 0) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC-QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_requests_duration_ms_count{env=\"$env\", service_group=\"$service_group\", service_name=\"$service_name\"}[2m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC-AVG-Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(increase(rpc_server_requests_duration_ms_sum{env=\"$env\", service_group=\"$service_group\", service_name=\"$service_name\"}[2m]) / increase(rpc_server_requests_duration_ms_count{env=\"$env\", service_group=\"$service_group\", service_name=\"$service_name\"}[2m]) > 0) by (method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}